-- Gestion Stock: instalacion y migracion multiempresa para SSMS.
-- Generado por npm run db:build-script. No editar las copias del esquema aqui.
-- Conserva los datos existentes y los asigna a Atomik al migrar por primera vez.
-- Requiere SQL Server 2016+ y permisos para crear bases/tablas.
-- Luego ejecutar npm run db:migrate para cargar las rutas iniciales de Atomik desde .env.
USE [master];
GO
IF DB_ID(N'GESTION_STOCK') IS NULL EXEC(N'CREATE DATABASE [GESTION_STOCK]');
GO
USE [GESTION_STOCK];
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
IF DB_NAME() <> N'GESTION_STOCK' THROW 50001, 'La base activa debe ser GESTION_STOCK.', 1;
IF (SELECT compatibility_level FROM sys.databases WHERE name=DB_NAME()) < 130
  THROW 50002, 'El importador requiere compatibilidad 130 o superior.', 1;
BEGIN TRY
  BEGIN TRANSACTION;
  EXEC(N'IF OBJECT_ID(''dbo.USERS'', ''U'') IS NULL
BEGIN
  CREATE TABLE dbo.USERS (
    ID_USER INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(80) NOT NULL,
    FULL_NAME VARCHAR(150) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ROLE VARCHAR(20) NOT NULL,
    ACTIVE BIT NOT NULL CONSTRAINT DF_USERS_ACTIVE DEFAULT 1,
    CREATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_USERS_CREATED DEFAULT SYSDATETIME(),
    UPDATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_USERS_UPDATED DEFAULT SYSDATETIME(),
    CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME),
    CONSTRAINT CK_USERS_ROLE CHECK (ROLE IN (''ADMIN'', ''CONSULTA''))
  );
END;

IF OBJECT_ID(''dbo.STOCK_IMPORTS'', ''U'') IS NULL
BEGIN
  CREATE TABLE dbo.STOCK_IMPORTS (
    ID_IMPORT BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    STARTED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_IMPORT_STARTED DEFAULT SYSDATETIME(),
    FINISHED_AT DATETIME2(0) NULL,
    STATUS VARCHAR(20) NOT NULL,
    SOURCE_FILE NVARCHAR(1000) NOT NULL,
    SOURCE_MODIFIED_AT DATETIME2(0) NULL,
    SOURCE_SIZE_BYTES BIGINT NULL,
    ROW_COUNT INT NULL,
    STOCK_TOTAL DECIMAL(19,4) NULL,
    ERROR_MESSAGE NVARCHAR(2000) NULL,
    EXCEL_STATUS VARCHAR(20) NULL,
    EXCEL_ERROR NVARCHAR(2000) NULL,
    TRIGGERED_BY VARCHAR(20) NOT NULL,
    ID_USER INT NULL,
    CONSTRAINT CK_IMPORT_STATUS CHECK (STATUS IN (''RUNNING'',''SUCCESS'',''ERROR'')),
    CONSTRAINT CK_IMPORT_EXCEL_STATUS CHECK (EXCEL_STATUS IS NULL OR EXCEL_STATUS IN (''PENDING'',''SUCCESS'',''ERROR'')),
    CONSTRAINT FK_IMPORT_USER FOREIGN KEY (ID_USER) REFERENCES dbo.USERS(ID_USER)
  );
END;

IF COL_LENGTH(''dbo.STOCK_IMPORTS'',''EXCEL_STATUS'') IS NULL
  ALTER TABLE dbo.STOCK_IMPORTS ADD EXCEL_STATUS VARCHAR(20) NULL;
IF COL_LENGTH(''dbo.STOCK_IMPORTS'',''EXCEL_ERROR'') IS NULL
  ALTER TABLE dbo.STOCK_IMPORTS ADD EXCEL_ERROR NVARCHAR(2000) NULL;

IF OBJECT_ID(''dbo.PRODUCT_CLASSIFICATION'', ''U'') IS NULL
BEGIN
  CREATE TABLE dbo.PRODUCT_CLASSIFICATION (
    COD_ALFA VARCHAR(30) NOT NULL PRIMARY KEY,
    CLASSIFICATION VARCHAR(20) NOT NULL,
    UPDATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_CLASS_UPDATED DEFAULT SYSDATETIME(),
    UPDATED_BY INT NOT NULL,
    CONSTRAINT CK_PRODUCT_CLASS CHECK (CLASSIFICATION IN (''MODULOS'',''ACCIONADO'')),
    CONSTRAINT FK_CLASS_USER FOREIGN KEY (UPDATED_BY) REFERENCES dbo.USERS(ID_USER)
  );
END;

IF OBJECT_ID(''dbo.STOCK_CURRENT'', ''U'') IS NULL
BEGIN
  CREATE TABLE dbo.STOCK_CURRENT (
    ID_STOCK BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    RUBRO VARCHAR(40) NOT NULL,
    COD_ALFA VARCHAR(30) NOT NULL,
    CODIGO VARCHAR(30) NOT NULL,
    DMODC VARCHAR(150) NOT NULL,
    DET_LINEA VARCHAR(80) NOT NULL,
    DCOLORC VARCHAR(100) NOT NULL,
    PARES INT NOT NULL,
    DTALLC VARCHAR(150) NOT NULL,
    SEXO VARCHAR(20) NOT NULL,
    EDAD VARCHAR(30) NOT NULL,
    PRECIO DECIMAL(19,4) NOT NULL,
    NOMBRE VARCHAR(150) NULL,
    T01 INT NOT NULL, T02 INT NOT NULL, T03 INT NOT NULL, T04 INT NOT NULL,
    T05 INT NOT NULL, T06 INT NOT NULL, T07 INT NOT NULL, T08 INT NOT NULL,
    T10 INT NOT NULL, T12 INT NOT NULL, T14 INT NOT NULL, T15 INT NOT NULL,
    T16 INT NOT NULL, T17 INT NOT NULL, T18 INT NOT NULL, T19 INT NOT NULL,
    T20 INT NOT NULL, T21 INT NOT NULL, T22 INT NOT NULL, T23 INT NOT NULL,
    T24 INT NOT NULL, T25 INT NOT NULL, T26 INT NOT NULL, T27 INT NOT NULL,
    T28 INT NOT NULL, T29 INT NOT NULL, T30 INT NOT NULL, T31 INT NOT NULL,
    T32 INT NOT NULL, T33 INT NOT NULL, T34 INT NOT NULL, T35 INT NOT NULL,
    T36 INT NOT NULL, T37 INT NOT NULL, T38 INT NOT NULL, T39 INT NOT NULL,
    T40 INT NOT NULL, T41 INT NOT NULL, T42 INT NOT NULL, T43 INT NOT NULL,
    T44 INT NOT NULL, T45 INT NOT NULL, T46 INT NOT NULL, T47 INT NOT NULL,
    T48 INT NOT NULL, T49 INT NOT NULL, T50 INT NOT NULL,
    T_2XL INT NOT NULL, T_3XL INT NOT NULL, T_L INT NOT NULL, T_M INT NOT NULL,
    T_S INT NOT NULL, T_XL INT NOT NULL, T_XS INT NOT NULL,
    STOCK DECIMAL(19,4) NOT NULL,
    DEPOSITO INT NOT NULL,
    NIVEL INT NOT NULL,
    TALLC VARCHAR(30) NOT NULL,
    DISCIPLINA VARCHAR(80) NULL,
    DTOESP DECIMAL(9,3) NOT NULL,
    P_BAS DECIMAL(19,4) NOT NULL,
    ESTADIO VARCHAR(20) NULL,
    IMPORTED_AT DATETIME2(0) NOT NULL,
    ID_IMPORT BIGINT NOT NULL,
    CONSTRAINT UQ_STOCK_CURRENT UNIQUE (COD_ALFA, DEPOSITO, NIVEL),
    CONSTRAINT FK_CURRENT_IMPORT FOREIGN KEY (ID_IMPORT) REFERENCES dbo.STOCK_IMPORTS(ID_IMPORT)
  );
  CREATE INDEX IX_STOCK_CURRENT_FILTERS ON dbo.STOCK_CURRENT (DEPOSITO, DMODC, DCOLORC);
END;

IF OBJECT_ID(''dbo.STOCK_HISTORY'', ''U'') IS NULL
BEGIN
  CREATE TABLE dbo.STOCK_HISTORY (
    ID_HISTORY BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    SNAPSHOT_DATE DATE NOT NULL,
    COD_ALFA VARCHAR(30) NOT NULL,
    CODIGO VARCHAR(30) NOT NULL,
    DEPOSITO INT NOT NULL,
    NIVEL INT NOT NULL,
    STOCK DECIMAL(19,4) NOT NULL,
    PRECIO DECIMAL(19,4) NOT NULL,
    P_BAS DECIMAL(19,4) NOT NULL,
    ID_IMPORT BIGINT NOT NULL,
    CREATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_HISTORY_CREATED DEFAULT SYSDATETIME(),
    CONSTRAINT UQ_STOCK_HISTORY UNIQUE (SNAPSHOT_DATE, COD_ALFA, DEPOSITO, NIVEL),
    CONSTRAINT FK_HISTORY_IMPORT FOREIGN KEY (ID_IMPORT) REFERENCES dbo.STOCK_IMPORTS(ID_IMPORT)
  );
  CREATE INDEX IX_STOCK_HISTORY_PRODUCT_DATE ON dbo.STOCK_HISTORY (COD_ALFA, SNAPSHOT_DATE DESC);
END;

IF OBJECT_ID(''dbo.CLASSIFICATION_AUDIT'', ''U'') IS NULL
BEGIN
  CREATE TABLE dbo.CLASSIFICATION_AUDIT (
    ID_AUDIT BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    COD_ALFA VARCHAR(30) NOT NULL,
    PREVIOUS_CLASSIFICATION VARCHAR(20) NULL,
    NEW_CLASSIFICATION VARCHAR(20) NOT NULL,
    ID_USER INT NOT NULL,
    CREATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_AUDIT_CREATED DEFAULT SYSDATETIME(),
    CONSTRAINT FK_AUDIT_USER FOREIGN KEY (ID_USER) REFERENCES dbo.USERS(ID_USER)
  );
END;
');
  EXEC(N'IF OBJECT_ID(''dbo.EMPRESAS'', ''U'') IS NULL
BEGIN
  CREATE TABLE dbo.EMPRESAS (
    ID_EMPRESA INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_EMPRESAS PRIMARY KEY,
    CODIGO VARCHAR(40) NOT NULL CONSTRAINT UQ_EMPRESAS_CODIGO UNIQUE,
    NOMBRE NVARCHAR(150) NOT NULL,
    ACTIVE BIT NOT NULL CONSTRAINT DF_EMPRESAS_ACTIVE DEFAULT 1,
    SOURCE_FILE NVARCHAR(400) COLLATE Latin1_General_100_CI_AS NULL,
    EXCEL_PATH NVARCHAR(400) COLLATE Latin1_General_100_CI_AS NULL,
    PUBLIC_PRICE_FACTOR DECIMAL(9,4) NOT NULL DEFAULT 1.85,
    RETENTION_DAYS INT NOT NULL DEFAULT 30,
    CREATED_AT DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
    CONSTRAINT CK_EMPRESAS_FACTOR CHECK (PUBLIC_PRICE_FACTOR > 0),
    CONSTRAINT CK_EMPRESAS_RETENTION CHECK (RETENTION_DAYS > 0)
  );
  CREATE UNIQUE INDEX UQ_EMPRESAS_SOURCE ON dbo.EMPRESAS(SOURCE_FILE) WHERE SOURCE_FILE IS NOT NULL;
  CREATE UNIQUE INDEX UQ_EMPRESAS_EXCEL ON dbo.EMPRESAS(EXCEL_PATH) WHERE EXCEL_PATH IS NOT NULL;
  INSERT dbo.EMPRESAS(CODIGO,NOMBRE) VALUES (''0'',N''Atomik'');
END;
');
  EXEC(N'
DECLARE @empresa INT=(SELECT ID_EMPRESA FROM dbo.EMPRESAS WHERE CODIGO=''0'');
IF @empresa IS NULL SET @empresa=(SELECT ID_EMPRESA FROM dbo.EMPRESAS WHERE CODIGO=''ATOMIK'');
DECLARE @table SYSNAME, @statement NVARCHAR(MAX);
DECLARE tables_cursor CURSOR LOCAL FAST_FORWARD FOR
  SELECT name FROM sys.tables WHERE schema_id=SCHEMA_ID(''dbo'') AND name IN
  (''USERS'',''STOCK_IMPORTS'',''STOCK_CURRENT'',''STOCK_HISTORY'',''PRODUCT_CLASSIFICATION'',''CLASSIFICATION_AUDIT'');
OPEN tables_cursor;
FETCH NEXT FROM tables_cursor INTO @table;
WHILE @@FETCH_STATUS=0
BEGIN
  IF COL_LENGTH(''dbo.''+@table,''ID_EMPRESA'') IS NULL
  BEGIN
    SET @statement=N''ALTER TABLE dbo.''+QUOTENAME(@table)+N'' ADD ID_EMPRESA INT NULL;'';
    EXEC sp_executesql @statement;
    SET @statement=N''UPDATE dbo.''+QUOTENAME(@table)+N'' SET ID_EMPRESA=@id; ALTER TABLE dbo.''+QUOTENAME(@table)+N'' ALTER COLUMN ID_EMPRESA INT NOT NULL; ALTER TABLE dbo.''+QUOTENAME(@table)+N'' ADD CONSTRAINT ''+QUOTENAME(''FK_''+@table+''_EMPRESA'')+N'' FOREIGN KEY(ID_EMPRESA) REFERENCES dbo.EMPRESAS(ID_EMPRESA);'';
    EXEC sp_executesql @statement,N''@id INT'',@id=@empresa;
  END;
  FETCH NEXT FROM tables_cursor INTO @table;
END;
CLOSE tables_cursor;
DEALLOCATE tables_cursor;
');
  EXEC(N'
IF OBJECT_ID(''dbo.UQ_USERS_USERNAME'',''UQ'') IS NOT NULL
  ALTER TABLE dbo.USERS DROP CONSTRAINT UQ_USERS_USERNAME;
IF OBJECT_ID(''dbo.UQ_USERS_EMPRESA_USERNAME'',''UQ'') IS NULL
  ALTER TABLE dbo.USERS ADD CONSTRAINT UQ_USERS_EMPRESA_USERNAME UNIQUE(ID_EMPRESA,USERNAME);

IF OBJECT_ID(''dbo.UQ_STOCK_CURRENT'',''UQ'') IS NOT NULL
  ALTER TABLE dbo.STOCK_CURRENT DROP CONSTRAINT UQ_STOCK_CURRENT;
IF OBJECT_ID(''dbo.UQ_CURRENT_EMPRESA'',''UQ'') IS NULL
  ALTER TABLE dbo.STOCK_CURRENT ADD CONSTRAINT UQ_CURRENT_EMPRESA UNIQUE(ID_EMPRESA,COD_ALFA,DEPOSITO,NIVEL);
IF OBJECT_ID(''dbo.UQ_STOCK_HISTORY'',''UQ'') IS NOT NULL
  ALTER TABLE dbo.STOCK_HISTORY DROP CONSTRAINT UQ_STOCK_HISTORY;
IF OBJECT_ID(''dbo.UQ_HISTORY_EMPRESA'',''UQ'') IS NULL
  ALTER TABLE dbo.STOCK_HISTORY ADD CONSTRAINT UQ_HISTORY_EMPRESA UNIQUE(ID_EMPRESA,SNAPSHOT_DATE,COD_ALFA,DEPOSITO,NIVEL);

IF NOT EXISTS(SELECT 1 FROM sys.index_columns ic JOIN sys.columns c ON c.object_id=ic.object_id AND c.column_id=ic.column_id JOIN sys.indexes i ON i.object_id=ic.object_id AND i.index_id=ic.index_id WHERE i.object_id=OBJECT_ID(''dbo.PRODUCT_CLASSIFICATION'') AND i.is_primary_key=1 AND c.name=''ID_EMPRESA'')
BEGIN
  DECLARE @pk SYSNAME=(SELECT name FROM sys.key_constraints WHERE parent_object_id=OBJECT_ID(''dbo.PRODUCT_CLASSIFICATION'') AND type=''PK'');
  DECLARE @dropPk NVARCHAR(MAX)=N''ALTER TABLE dbo.PRODUCT_CLASSIFICATION DROP CONSTRAINT ''+QUOTENAME(@pk);
  EXEC sp_executesql @dropPk;
  ALTER TABLE dbo.PRODUCT_CLASSIFICATION ADD CONSTRAINT PK_CLASSIFICATION_EMPRESA PRIMARY KEY(ID_EMPRESA,COD_ALFA);
END;

IF OBJECT_ID(''dbo.UQ_USERS_EMPRESA_ID'',''UQ'') IS NULL
  ALTER TABLE dbo.USERS ADD CONSTRAINT UQ_USERS_EMPRESA_ID UNIQUE(ID_EMPRESA,ID_USER);
IF OBJECT_ID(''dbo.UQ_IMPORT_EMPRESA_ID'',''UQ'') IS NULL
  ALTER TABLE dbo.STOCK_IMPORTS ADD CONSTRAINT UQ_IMPORT_EMPRESA_ID UNIQUE(ID_EMPRESA,ID_IMPORT);
IF OBJECT_ID(''dbo.FK_IMPORT_EMPRESA_USER'',''F'') IS NULL
  ALTER TABLE dbo.STOCK_IMPORTS ADD CONSTRAINT FK_IMPORT_EMPRESA_USER FOREIGN KEY(ID_EMPRESA,ID_USER) REFERENCES dbo.USERS(ID_EMPRESA,ID_USER);
IF OBJECT_ID(''dbo.FK_CURRENT_EMPRESA_IMPORT'',''F'') IS NULL
  ALTER TABLE dbo.STOCK_CURRENT ADD CONSTRAINT FK_CURRENT_EMPRESA_IMPORT FOREIGN KEY(ID_EMPRESA,ID_IMPORT) REFERENCES dbo.STOCK_IMPORTS(ID_EMPRESA,ID_IMPORT);
IF OBJECT_ID(''dbo.FK_HISTORY_EMPRESA_IMPORT'',''F'') IS NULL
  ALTER TABLE dbo.STOCK_HISTORY ADD CONSTRAINT FK_HISTORY_EMPRESA_IMPORT FOREIGN KEY(ID_EMPRESA,ID_IMPORT) REFERENCES dbo.STOCK_IMPORTS(ID_EMPRESA,ID_IMPORT);
IF OBJECT_ID(''dbo.FK_CLASS_EMPRESA_USER'',''F'') IS NULL
  ALTER TABLE dbo.PRODUCT_CLASSIFICATION ADD CONSTRAINT FK_CLASS_EMPRESA_USER FOREIGN KEY(ID_EMPRESA,UPDATED_BY) REFERENCES dbo.USERS(ID_EMPRESA,ID_USER);
IF OBJECT_ID(''dbo.FK_AUDIT_EMPRESA_USER'',''F'') IS NULL
  ALTER TABLE dbo.CLASSIFICATION_AUDIT ADD CONSTRAINT FK_AUDIT_EMPRESA_USER FOREIGN KEY(ID_EMPRESA,ID_USER) REFERENCES dbo.USERS(ID_EMPRESA,ID_USER);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(''dbo.STOCK_IMPORTS'') AND name=''IX_IMPORT_EMPRESA_DATE'')
  CREATE INDEX IX_IMPORT_EMPRESA_DATE ON dbo.STOCK_IMPORTS(ID_EMPRESA,ID_IMPORT DESC);
');
  EXEC(N'IF COL_LENGTH(''dbo.STOCK_CURRENT'',''COLORC'') IS NULL
  ALTER TABLE dbo.STOCK_CURRENT ADD COLORC VARCHAR(30) NULL;
IF COL_LENGTH(''dbo.STOCK_CURRENT'',''COD_TEM'') IS NULL
  ALTER TABLE dbo.STOCK_CURRENT ADD COD_TEM VARCHAR(30) NULL;
IF COL_LENGTH(''dbo.STOCK_CURRENT'',''COD_ANIO'') IS NULL
  ALTER TABLE dbo.STOCK_CURRENT ADD COD_ANIO VARCHAR(30) NULL;
IF COL_LENGTH(''dbo.STOCK_CURRENT'',''MODC'') IS NULL
  ALTER TABLE dbo.STOCK_CURRENT ADD MODC VARCHAR(30) NULL;
IF COL_LENGTH(''dbo.EMPRESAS'',''IMAGE_DIRECTORY'') IS NULL
  ALTER TABLE dbo.EMPRESAS ADD IMAGE_DIRECTORY NVARCHAR(400) NULL;
');
  EXEC(N'-- Descripciones opcionales: el TXT puede no informarlas, especialmente en indumentaria.
ALTER TABLE dbo.STOCK_CURRENT ALTER COLUMN EDAD VARCHAR(30) NULL;
ALTER TABLE dbo.STOCK_CURRENT ALTER COLUMN SEXO VARCHAR(20) NULL;
ALTER TABLE dbo.STOCK_CURRENT ALTER COLUMN DET_LINEA VARCHAR(80) NULL;
ALTER TABLE dbo.STOCK_CURRENT ALTER COLUMN DTALLC VARCHAR(150) NULL;
ALTER TABLE dbo.STOCK_CURRENT ALTER COLUMN TALLC VARCHAR(30) NULL;
');
  EXEC(N'IF OBJECT_ID(''dbo.STOCK_GRIDS'',''U'') IS NULL
BEGIN
  CREATE TABLE dbo.STOCK_GRIDS (
    ID_GRID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_STOCK_GRIDS PRIMARY KEY,
    ID_EMPRESA INT NOT NULL,
    NAME NVARCHAR(150) NOT NULL,
    RULES_JSON NVARCHAR(MAX) NOT NULL,
    ACTIVE BIT NOT NULL CONSTRAINT DF_GRIDS_ACTIVE DEFAULT 1,
    VERSION INT NOT NULL CONSTRAINT DF_GRIDS_VERSION DEFAULT 1,
    CREATED_BY INT NOT NULL,
    UPDATED_BY INT NOT NULL,
    CREATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_GRIDS_CREATED DEFAULT SYSDATETIME(),
    UPDATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_GRIDS_UPDATED DEFAULT SYSDATETIME(),
    CONSTRAINT CK_GRIDS_JSON CHECK (ISJSON(RULES_JSON)=1),
    CONSTRAINT FK_GRIDS_EMPRESA FOREIGN KEY(ID_EMPRESA) REFERENCES dbo.EMPRESAS(ID_EMPRESA),
    CONSTRAINT FK_GRIDS_CREATOR FOREIGN KEY(ID_EMPRESA,CREATED_BY) REFERENCES dbo.USERS(ID_EMPRESA,ID_USER),
    CONSTRAINT FK_GRIDS_UPDATER FOREIGN KEY(ID_EMPRESA,UPDATED_BY) REFERENCES dbo.USERS(ID_EMPRESA,ID_USER)
  );
  CREATE UNIQUE INDEX UQ_GRID_ACTIVE_NAME ON dbo.STOCK_GRIDS(ID_EMPRESA,NAME) WHERE ACTIVE=1;
END;
');
  EXEC(N'IF COL_LENGTH(''dbo.STOCK_GRIDS'',''EXPORT_ENABLED'') IS NULL
BEGIN
  ALTER TABLE dbo.STOCK_GRIDS ADD
    EXPORT_ENABLED BIT NOT NULL CONSTRAINT DF_GRID_EXPORT_ENABLED DEFAULT 0,
    EXPORT_TIME CHAR(5) NULL,
    EXPORT_PATH NVARCHAR(400) NULL,
    EXPORT_LAST_DATE DATE NULL,
    EXPORT_STATUS VARCHAR(20) NULL,
    EXPORT_FINISHED_AT DATETIMEOFFSET NULL,
    EXPORT_ERROR NVARCHAR(2000) NULL;
END;
');
  EXEC(N'
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name=''UX_GRID_EXPORT_PATH'' AND object_id=OBJECT_ID(''dbo.STOCK_GRIDS''))
  CREATE UNIQUE INDEX UX_GRID_EXPORT_PATH ON dbo.STOCK_GRIDS(EXPORT_PATH)
    WHERE ACTIVE=1 AND EXPORT_ENABLED=1 AND EXPORT_PATH IS NOT NULL;
');
  EXEC(N'IF COL_LENGTH(''dbo.STOCK_CURRENT'',''LICENCIA'') IS NULL
  ALTER TABLE dbo.STOCK_CURRENT ADD LICENCIA NVARCHAR(150) NULL;
');
  EXEC(N'IF COL_LENGTH(''dbo.STOCK_CURRENT'',''MARCA'') IS NULL
  ALTER TABLE dbo.STOCK_CURRENT ADD MARCA NVARCHAR(150) NULL;
IF COL_LENGTH(''dbo.STOCK_CURRENT'',''LISTA'') IS NULL
  ALTER TABLE dbo.STOCK_CURRENT ADD LISTA NVARCHAR(30) NULL;
IF COL_LENGTH(''dbo.STOCK_CURRENT'',''VERSION'') IS NULL
  ALTER TABLE dbo.STOCK_CURRENT ADD VERSION NVARCHAR(30) NULL;
');
  EXEC(N'IF OBJECT_ID(''dbo.STOCK_PRICES'',''U'') IS NULL
BEGIN
  CREATE TABLE dbo.STOCK_PRICES (
    ID_EMPRESA INT NOT NULL REFERENCES dbo.EMPRESAS(ID_EMPRESA),
    COD_ALFA VARCHAR(30) NOT NULL,
    DEPOSITO INT NOT NULL,
    NIVEL INT NOT NULL,
    LISTA NVARCHAR(30) NOT NULL,
    VERSION NVARCHAR(30) NOT NULL,
    PRECIO DECIMAL(19,4) NOT NULL,
    P_BAS DECIMAL(19,4) NULL,
    DTOESP DECIMAL(9,3) NULL,
    CONSTRAINT PK_STOCK_PRICES PRIMARY KEY(ID_EMPRESA,COD_ALFA,DEPOSITO,NIVEL,LISTA,VERSION)
  );
END;
');
  EXEC(N'-- El ingreso identifica al usuario sin solicitar empresa.
-- No renombrar ni unir cuentas existentes automaticamente.
IF EXISTS (SELECT USERNAME FROM dbo.USERS GROUP BY USERNAME HAVING COUNT(*) > 1)
  THROW 50010, ''Hay nombres de usuario repetidos entre empresas. Asigne nombres unicos antes de migrar.'', 1;
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(''dbo.USERS'') AND name=''UQ_USERS_LOGIN'')
  CREATE UNIQUE INDEX UQ_USERS_LOGIN ON dbo.USERS(USERNAME);
');
  EXEC(N'IF COL_LENGTH(''dbo.USERS'',''IS_SUPERADMIN'') IS NULL
  ALTER TABLE dbo.USERS ADD IS_SUPERADMIN BIT NOT NULL CONSTRAINT DF_USERS_SUPERADMIN DEFAULT 0;
');
  EXEC(N'-- Cambia el codigo comercial; conserva el ID interno y todas las asociaciones.
IF EXISTS(SELECT 1 FROM dbo.EMPRESAS WHERE CODIGO=''ATOMIK'')
BEGIN
  IF EXISTS(SELECT 1 FROM dbo.EMPRESAS WHERE CODIGO=''0'')
    THROW 50012, ''El codigo 0 ya pertenece a una empresa. Revise las empresas antes de migrar Atomik.'', 1;
  UPDATE dbo.EMPRESAS SET CODIGO=''0'' WHERE CODIGO=''ATOMIK'';
END;
');
  EXEC(N'-- El autor puede ser un superadministrador de otra empresa.
-- ID_EMPRESA sigue identificando al propietario del registro.
-- Conservar el ID del autor real, sin crear cuentas duplicadas ni moverlas.
DECLARE @table SYSNAME, @constraint SYSNAME, @column SYSNAME, @statement NVARCHAR(MAX);
DECLARE actors CURSOR LOCAL FAST_FORWARD FOR
  SELECT * FROM (VALUES
    (''STOCK_IMPORTS'',''FK_IMPORT_EMPRESA_USER'',''ID_USER''),
    (''PRODUCT_CLASSIFICATION'',''FK_CLASS_EMPRESA_USER'',''UPDATED_BY''),
    (''CLASSIFICATION_AUDIT'',''FK_AUDIT_EMPRESA_USER'',''ID_USER''),
    (''STOCK_GRIDS'',''FK_GRIDS_CREATOR'',''CREATED_BY''),
    (''STOCK_GRIDS'',''FK_GRIDS_UPDATER'',''UPDATED_BY'')
  ) M(table_name,constraint_name,column_name);
OPEN actors;
FETCH NEXT FROM actors INTO @table,@constraint,@column;
WHILE @@FETCH_STATUS=0
BEGIN
  IF (SELECT COUNT(*) FROM sys.foreign_key_columns WHERE constraint_object_id=OBJECT_ID(''dbo.''+@constraint)) > 1
  BEGIN
    SET @statement=N''ALTER TABLE dbo.''+QUOTENAME(@table)+N'' DROP CONSTRAINT ''+QUOTENAME(@constraint);
    EXEC sp_executesql @statement;
  END;
  IF OBJECT_ID(''dbo.''+@constraint,''F'') IS NULL
  BEGIN
    SET @statement=N''ALTER TABLE dbo.''+QUOTENAME(@table)+N'' WITH CHECK ADD CONSTRAINT ''+QUOTENAME(@constraint)
      +N'' FOREIGN KEY(''+QUOTENAME(@column)+N'') REFERENCES dbo.USERS(ID_USER)'';
    EXEC sp_executesql @statement;
  END;
  FETCH NEXT FROM actors INTO @table,@constraint,@column;
END;
CLOSE actors;
DEALLOCATE actors;
');
  EXEC(N'IF OBJECT_ID(''dbo.COMPANY_PRICE_FACTORS'',''U'') IS NULL
BEGIN
  CREATE TABLE dbo.COMPANY_PRICE_FACTORS (
    ID_EMPRESA INT NOT NULL REFERENCES dbo.EMPRESAS(ID_EMPRESA),
    MARCA NVARCHAR(150) NOT NULL,
    NIVEL INT NOT NULL CHECK (NIVEL IN (900,950)),
    FACTOR DECIMAL(9,4) NOT NULL CHECK (FACTOR>0),
    CONSTRAINT PK_COMPANY_PRICE_FACTORS PRIMARY KEY(ID_EMPRESA,MARCA,NIVEL)
  );
END;
');
  EXEC(N'IF COL_LENGTH(''dbo.COMPANY_PRICE_FACTORS'',''ESPECIFICO'') IS NULL
BEGIN
 ALTER TABLE dbo.COMPANY_PRICE_FACTORS ADD ESPECIFICO BIT NOT NULL CONSTRAINT DF_FACTOR_SCOPE DEFAULT 0,
 LICENCIA NVARCHAR(150) NOT NULL CONSTRAINT DF_FACTOR_LICENSE DEFAULT N'''',
 RUBRO NVARCHAR(40) NOT NULL CONSTRAINT DF_FACTOR_RUBRO DEFAULT N'''';
 ALTER TABLE dbo.COMPANY_PRICE_FACTORS DROP CONSTRAINT PK_COMPANY_PRICE_FACTORS;
END;
IF NOT EXISTS(SELECT 1 FROM sys.key_constraints WHERE name=''PK_COMPANY_PRICE_FACTORS'')
 EXEC(N''ALTER TABLE dbo.COMPANY_PRICE_FACTORS ADD CONSTRAINT PK_COMPANY_PRICE_FACTORS PRIMARY KEY(ID_EMPRESA,MARCA,NIVEL,ESPECIFICO,LICENCIA,RUBRO)'');
');
  EXEC(N'IF COL_LENGTH(''dbo.COMPANY_PRICE_FACTORS'',''LISTA'') IS NULL
BEGIN
 ALTER TABLE dbo.COMPANY_PRICE_FACTORS ADD LISTA NVARCHAR(30) NOT NULL CONSTRAINT DF_FACTOR_LIST DEFAULT N'''';
 ALTER TABLE dbo.COMPANY_PRICE_FACTORS DROP CONSTRAINT PK_COMPANY_PRICE_FACTORS;
END;
IF NOT EXISTS(SELECT 1 FROM sys.key_constraints WHERE name=''PK_COMPANY_PRICE_FACTORS'')
 EXEC(N''ALTER TABLE dbo.COMPANY_PRICE_FACTORS ADD CONSTRAINT PK_COMPANY_PRICE_FACTORS PRIMARY KEY(ID_EMPRESA,MARCA,NIVEL,ESPECIFICO,LICENCIA,RUBRO,LISTA)'');
');
  COMMIT TRANSACTION;
  PRINT N'GESTION_STOCK: esquema multiempresa disponible.';
END TRY
BEGIN CATCH
  IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
  THROW;
END CATCH;
GO
SELECT CODIGO,NOMBRE FROM dbo.EMPRESAS;
GO
