IF OBJECT_ID('dbo.USERS', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.USERS (
    ID_USER INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    USERNAME VARCHAR(80) NOT NULL,
    FULL_NAME VARCHAR(150) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ROLE VARCHAR(20) NOT NULL,
    ACTIVE BIT NOT NULL CONSTRAINT DF_USERS_ACTIVE DEFAULT 1,
    CREATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_USERS_CREATED DEFAULT SYSDATETIME(),
    UPDATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_USERS_UPDATED DEFAULT SYSDATETIME(),
    CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME),
    CONSTRAINT CK_USERS_ROLE CHECK (ROLE IN ('ADMIN', 'CONSULTA'))
  );
END;

IF OBJECT_ID('dbo.STOCK_IMPORTS', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.STOCK_IMPORTS (
    ID_IMPORT BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    STARTED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_IMPORT_STARTED DEFAULT SYSDATETIME(),
    FINISHED_AT DATETIME2(0) NULL,
    STATUS VARCHAR(20) NOT NULL,
    SOURCE_FILE NVARCHAR(1000) NOT NULL,
    SOURCE_MODIFIED_AT DATETIME2(0) NULL,
    SOURCE_SIZE_BYTES BIGINT NULL,
    ROW_COUNT INT NULL,
    STOCK_TOTAL DECIMAL(19,4) NULL,
    ERROR_MESSAGE NVARCHAR(2000) NULL,
    EXCEL_STATUS VARCHAR(20) NULL,
    EXCEL_ERROR NVARCHAR(2000) NULL,
    TRIGGERED_BY VARCHAR(20) NOT NULL,
    ID_USER INT NULL,
    CONSTRAINT CK_IMPORT_STATUS CHECK (STATUS IN ('RUNNING','SUCCESS','ERROR')),
    CONSTRAINT CK_IMPORT_EXCEL_STATUS CHECK (EXCEL_STATUS IS NULL OR EXCEL_STATUS IN ('PENDING','SUCCESS','ERROR')),
    CONSTRAINT FK_IMPORT_USER FOREIGN KEY (ID_USER) REFERENCES dbo.USERS(ID_USER)
  );
END;

IF COL_LENGTH('dbo.STOCK_IMPORTS','EXCEL_STATUS') IS NULL
  ALTER TABLE dbo.STOCK_IMPORTS ADD EXCEL_STATUS VARCHAR(20) NULL;
IF COL_LENGTH('dbo.STOCK_IMPORTS','EXCEL_ERROR') IS NULL
  ALTER TABLE dbo.STOCK_IMPORTS ADD EXCEL_ERROR NVARCHAR(2000) NULL;

IF OBJECT_ID('dbo.PRODUCT_CLASSIFICATION', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.PRODUCT_CLASSIFICATION (
    COD_ALFA VARCHAR(30) NOT NULL PRIMARY KEY,
    CLASSIFICATION VARCHAR(20) NOT NULL,
    UPDATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_CLASS_UPDATED DEFAULT SYSDATETIME(),
    UPDATED_BY INT NOT NULL,
    CONSTRAINT CK_PRODUCT_CLASS CHECK (CLASSIFICATION IN ('MODULOS','ACCIONADO')),
    CONSTRAINT FK_CLASS_USER FOREIGN KEY (UPDATED_BY) REFERENCES dbo.USERS(ID_USER)
  );
END;

IF OBJECT_ID('dbo.STOCK_CURRENT', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.STOCK_CURRENT (
    ID_STOCK BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    RUBRO VARCHAR(40) NOT NULL,
    COD_ALFA VARCHAR(30) NOT NULL,
    CODIGO VARCHAR(30) NOT NULL,
    DMODC VARCHAR(150) NOT NULL,
    DET_LINEA VARCHAR(80) NOT NULL,
    DCOLORC VARCHAR(100) NOT NULL,
    PARES INT NOT NULL,
    DTALLC VARCHAR(150) NOT NULL,
    SEXO VARCHAR(20) NOT NULL,
    EDAD VARCHAR(30) NOT NULL,
    PRECIO DECIMAL(19,4) NOT NULL,
    NOMBRE VARCHAR(150) NULL,
    T01 INT NOT NULL, T02 INT NOT NULL, T03 INT NOT NULL, T04 INT NOT NULL,
    T05 INT NOT NULL, T06 INT NOT NULL, T07 INT NOT NULL, T08 INT NOT NULL,
    T10 INT NOT NULL, T12 INT NOT NULL, T14 INT NOT NULL, T15 INT NOT NULL,
    T16 INT NOT NULL, T17 INT NOT NULL, T18 INT NOT NULL, T19 INT NOT NULL,
    T20 INT NOT NULL, T21 INT NOT NULL, T22 INT NOT NULL, T23 INT NOT NULL,
    T24 INT NOT NULL, T25 INT NOT NULL, T26 INT NOT NULL, T27 INT NOT NULL,
    T28 INT NOT NULL, T29 INT NOT NULL, T30 INT NOT NULL, T31 INT NOT NULL,
    T32 INT NOT NULL, T33 INT NOT NULL, T34 INT NOT NULL, T35 INT NOT NULL,
    T36 INT NOT NULL, T37 INT NOT NULL, T38 INT NOT NULL, T39 INT NOT NULL,
    T40 INT NOT NULL, T41 INT NOT NULL, T42 INT NOT NULL, T43 INT NOT NULL,
    T44 INT NOT NULL, T45 INT NOT NULL, T46 INT NOT NULL, T47 INT NOT NULL,
    T48 INT NOT NULL, T49 INT NOT NULL, T50 INT NOT NULL,
    T_2XL INT NOT NULL, T_3XL INT NOT NULL, T_L INT NOT NULL, T_M INT NOT NULL,
    T_S INT NOT NULL, T_XL INT NOT NULL, T_XS INT NOT NULL,
    STOCK DECIMAL(19,4) NOT NULL,
    DEPOSITO INT NOT NULL,
    NIVEL INT NOT NULL,
    TALLC VARCHAR(30) NOT NULL,
    DISCIPLINA VARCHAR(80) NULL,
    DTOESP DECIMAL(9,3) NOT NULL,
    P_BAS DECIMAL(19,4) NOT NULL,
    ESTADIO VARCHAR(20) NULL,
    IMPORTED_AT DATETIME2(0) NOT NULL,
    ID_IMPORT BIGINT NOT NULL,
    CONSTRAINT UQ_STOCK_CURRENT UNIQUE (COD_ALFA, DEPOSITO, NIVEL),
    CONSTRAINT FK_CURRENT_IMPORT FOREIGN KEY (ID_IMPORT) REFERENCES dbo.STOCK_IMPORTS(ID_IMPORT)
  );
  CREATE INDEX IX_STOCK_CURRENT_FILTERS ON dbo.STOCK_CURRENT (DEPOSITO, DMODC, DCOLORC);
END;

IF OBJECT_ID('dbo.STOCK_HISTORY', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.STOCK_HISTORY (
    ID_HISTORY BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    SNAPSHOT_DATE DATE NOT NULL,
    COD_ALFA VARCHAR(30) NOT NULL,
    CODIGO VARCHAR(30) NOT NULL,
    DEPOSITO INT NOT NULL,
    NIVEL INT NOT NULL,
    STOCK DECIMAL(19,4) NOT NULL,
    PRECIO DECIMAL(19,4) NOT NULL,
    P_BAS DECIMAL(19,4) NOT NULL,
    ID_IMPORT BIGINT NOT NULL,
    CREATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_HISTORY_CREATED DEFAULT SYSDATETIME(),
    CONSTRAINT UQ_STOCK_HISTORY UNIQUE (SNAPSHOT_DATE, COD_ALFA, DEPOSITO, NIVEL),
    CONSTRAINT FK_HISTORY_IMPORT FOREIGN KEY (ID_IMPORT) REFERENCES dbo.STOCK_IMPORTS(ID_IMPORT)
  );
  CREATE INDEX IX_STOCK_HISTORY_PRODUCT_DATE ON dbo.STOCK_HISTORY (COD_ALFA, SNAPSHOT_DATE DESC);
END;

IF OBJECT_ID('dbo.CLASSIFICATION_AUDIT', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.CLASSIFICATION_AUDIT (
    ID_AUDIT BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    COD_ALFA VARCHAR(30) NOT NULL,
    PREVIOUS_CLASSIFICATION VARCHAR(20) NULL,
    NEW_CLASSIFICATION VARCHAR(20) NOT NULL,
    ID_USER INT NOT NULL,
    CREATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_AUDIT_CREATED DEFAULT SYSDATETIME(),
    CONSTRAINT FK_AUDIT_USER FOREIGN KEY (ID_USER) REFERENCES dbo.USERS(ID_USER)
  );
END;
