IF OBJECT_ID('dbo.EMPRESAS', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.EMPRESAS (
    ID_EMPRESA INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_EMPRESAS PRIMARY KEY,
    CODIGO VARCHAR(40) NOT NULL CONSTRAINT UQ_EMPRESAS_CODIGO UNIQUE,
    NOMBRE NVARCHAR(150) NOT NULL,
    ACTIVE BIT NOT NULL CONSTRAINT DF_EMPRESAS_ACTIVE DEFAULT 1,
    SOURCE_FILE NVARCHAR(400) COLLATE Latin1_General_100_CI_AS NULL,
    EXCEL_PATH NVARCHAR(400) COLLATE Latin1_General_100_CI_AS NULL,
    PUBLIC_PRICE_FACTOR DECIMAL(9,4) NOT NULL DEFAULT 1.85,
    RETENTION_DAYS INT NOT NULL DEFAULT 30,
    CREATED_AT DATETIME2(0) NOT NULL DEFAULT SYSDATETIME(),
    CONSTRAINT CK_EMPRESAS_FACTOR CHECK (PUBLIC_PRICE_FACTOR > 0),
    CONSTRAINT CK_EMPRESAS_RETENTION CHECK (RETENTION_DAYS > 0)
  );
  CREATE UNIQUE INDEX UQ_EMPRESAS_SOURCE ON dbo.EMPRESAS(SOURCE_FILE) WHERE SOURCE_FILE IS NOT NULL;
  CREATE UNIQUE INDEX UQ_EMPRESAS_EXCEL ON dbo.EMPRESAS(EXCEL_PATH) WHERE EXCEL_PATH IS NOT NULL;
  INSERT dbo.EMPRESAS(CODIGO,NOMBRE) VALUES ('0',N'Atomik');
END;
GO
DECLARE @empresa INT=(SELECT ID_EMPRESA FROM dbo.EMPRESAS WHERE CODIGO='0');
IF @empresa IS NULL SET @empresa=(SELECT ID_EMPRESA FROM dbo.EMPRESAS WHERE CODIGO='ATOMIK');
DECLARE @table SYSNAME, @statement NVARCHAR(MAX);
DECLARE tables_cursor CURSOR LOCAL FAST_FORWARD FOR
  SELECT name FROM sys.tables WHERE schema_id=SCHEMA_ID('dbo') AND name IN
  ('USERS','STOCK_IMPORTS','STOCK_CURRENT','STOCK_HISTORY','PRODUCT_CLASSIFICATION','CLASSIFICATION_AUDIT');
OPEN tables_cursor;
FETCH NEXT FROM tables_cursor INTO @table;
WHILE @@FETCH_STATUS=0
BEGIN
  IF COL_LENGTH('dbo.'+@table,'ID_EMPRESA') IS NULL
  BEGIN
    SET @statement=N'ALTER TABLE dbo.'+QUOTENAME(@table)+N' ADD ID_EMPRESA INT NULL;';
    EXEC sp_executesql @statement;
    SET @statement=N'UPDATE dbo.'+QUOTENAME(@table)+N' SET ID_EMPRESA=@id; ALTER TABLE dbo.'+QUOTENAME(@table)+N' ALTER COLUMN ID_EMPRESA INT NOT NULL; ALTER TABLE dbo.'+QUOTENAME(@table)+N' ADD CONSTRAINT '+QUOTENAME('FK_'+@table+'_EMPRESA')+N' FOREIGN KEY(ID_EMPRESA) REFERENCES dbo.EMPRESAS(ID_EMPRESA);';
    EXEC sp_executesql @statement,N'@id INT',@id=@empresa;
  END;
  FETCH NEXT FROM tables_cursor INTO @table;
END;
CLOSE tables_cursor;
DEALLOCATE tables_cursor;
GO
IF OBJECT_ID('dbo.UQ_USERS_USERNAME','UQ') IS NOT NULL
  ALTER TABLE dbo.USERS DROP CONSTRAINT UQ_USERS_USERNAME;
IF OBJECT_ID('dbo.UQ_USERS_EMPRESA_USERNAME','UQ') IS NULL
  ALTER TABLE dbo.USERS ADD CONSTRAINT UQ_USERS_EMPRESA_USERNAME UNIQUE(ID_EMPRESA,USERNAME);

IF OBJECT_ID('dbo.UQ_STOCK_CURRENT','UQ') IS NOT NULL
  ALTER TABLE dbo.STOCK_CURRENT DROP CONSTRAINT UQ_STOCK_CURRENT;
IF OBJECT_ID('dbo.UQ_CURRENT_EMPRESA','UQ') IS NULL
  ALTER TABLE dbo.STOCK_CURRENT ADD CONSTRAINT UQ_CURRENT_EMPRESA UNIQUE(ID_EMPRESA,COD_ALFA,DEPOSITO,NIVEL);
IF OBJECT_ID('dbo.UQ_STOCK_HISTORY','UQ') IS NOT NULL
  ALTER TABLE dbo.STOCK_HISTORY DROP CONSTRAINT UQ_STOCK_HISTORY;
IF OBJECT_ID('dbo.UQ_HISTORY_EMPRESA','UQ') IS NULL
  ALTER TABLE dbo.STOCK_HISTORY ADD CONSTRAINT UQ_HISTORY_EMPRESA UNIQUE(ID_EMPRESA,SNAPSHOT_DATE,COD_ALFA,DEPOSITO,NIVEL);

IF NOT EXISTS(SELECT 1 FROM sys.index_columns ic JOIN sys.columns c ON c.object_id=ic.object_id AND c.column_id=ic.column_id JOIN sys.indexes i ON i.object_id=ic.object_id AND i.index_id=ic.index_id WHERE i.object_id=OBJECT_ID('dbo.PRODUCT_CLASSIFICATION') AND i.is_primary_key=1 AND c.name='ID_EMPRESA')
BEGIN
  DECLARE @pk SYSNAME=(SELECT name FROM sys.key_constraints WHERE parent_object_id=OBJECT_ID('dbo.PRODUCT_CLASSIFICATION') AND type='PK');
  DECLARE @dropPk NVARCHAR(MAX)=N'ALTER TABLE dbo.PRODUCT_CLASSIFICATION DROP CONSTRAINT '+QUOTENAME(@pk);
  EXEC sp_executesql @dropPk;
  ALTER TABLE dbo.PRODUCT_CLASSIFICATION ADD CONSTRAINT PK_CLASSIFICATION_EMPRESA PRIMARY KEY(ID_EMPRESA,COD_ALFA);
END;

IF OBJECT_ID('dbo.UQ_USERS_EMPRESA_ID','UQ') IS NULL
  ALTER TABLE dbo.USERS ADD CONSTRAINT UQ_USERS_EMPRESA_ID UNIQUE(ID_EMPRESA,ID_USER);
IF OBJECT_ID('dbo.UQ_IMPORT_EMPRESA_ID','UQ') IS NULL
  ALTER TABLE dbo.STOCK_IMPORTS ADD CONSTRAINT UQ_IMPORT_EMPRESA_ID UNIQUE(ID_EMPRESA,ID_IMPORT);
IF OBJECT_ID('dbo.FK_IMPORT_EMPRESA_USER','F') IS NULL
  ALTER TABLE dbo.STOCK_IMPORTS ADD CONSTRAINT FK_IMPORT_EMPRESA_USER FOREIGN KEY(ID_EMPRESA,ID_USER) REFERENCES dbo.USERS(ID_EMPRESA,ID_USER);
IF OBJECT_ID('dbo.FK_CURRENT_EMPRESA_IMPORT','F') IS NULL
  ALTER TABLE dbo.STOCK_CURRENT ADD CONSTRAINT FK_CURRENT_EMPRESA_IMPORT FOREIGN KEY(ID_EMPRESA,ID_IMPORT) REFERENCES dbo.STOCK_IMPORTS(ID_EMPRESA,ID_IMPORT);
IF OBJECT_ID('dbo.FK_HISTORY_EMPRESA_IMPORT','F') IS NULL
  ALTER TABLE dbo.STOCK_HISTORY ADD CONSTRAINT FK_HISTORY_EMPRESA_IMPORT FOREIGN KEY(ID_EMPRESA,ID_IMPORT) REFERENCES dbo.STOCK_IMPORTS(ID_EMPRESA,ID_IMPORT);
IF OBJECT_ID('dbo.FK_CLASS_EMPRESA_USER','F') IS NULL
  ALTER TABLE dbo.PRODUCT_CLASSIFICATION ADD CONSTRAINT FK_CLASS_EMPRESA_USER FOREIGN KEY(ID_EMPRESA,UPDATED_BY) REFERENCES dbo.USERS(ID_EMPRESA,ID_USER);
IF OBJECT_ID('dbo.FK_AUDIT_EMPRESA_USER','F') IS NULL
  ALTER TABLE dbo.CLASSIFICATION_AUDIT ADD CONSTRAINT FK_AUDIT_EMPRESA_USER FOREIGN KEY(ID_EMPRESA,ID_USER) REFERENCES dbo.USERS(ID_EMPRESA,ID_USER);
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('dbo.STOCK_IMPORTS') AND name='IX_IMPORT_EMPRESA_DATE')
  CREATE INDEX IX_IMPORT_EMPRESA_DATE ON dbo.STOCK_IMPORTS(ID_EMPRESA,ID_IMPORT DESC);
