IF COL_LENGTH('dbo.STOCK_CURRENT','COLORC') IS NULL
  ALTER TABLE dbo.STOCK_CURRENT ADD COLORC VARCHAR(30) NULL;
IF COL_LENGTH('dbo.STOCK_CURRENT','COD_TEM') IS NULL
  ALTER TABLE dbo.STOCK_CURRENT ADD COD_TEM VARCHAR(30) NULL;
IF COL_LENGTH('dbo.STOCK_CURRENT','COD_ANIO') IS NULL
  ALTER TABLE dbo.STOCK_CURRENT ADD COD_ANIO VARCHAR(30) NULL;
IF COL_LENGTH('dbo.STOCK_CURRENT','MODC') IS NULL
  ALTER TABLE dbo.STOCK_CURRENT ADD MODC VARCHAR(30) NULL;
IF COL_LENGTH('dbo.EMPRESAS','IMAGE_DIRECTORY') IS NULL
  ALTER TABLE dbo.EMPRESAS ADD IMAGE_DIRECTORY NVARCHAR(400) NULL;
