-- Descripciones opcionales: el TXT puede no informarlas, especialmente en indumentaria.
ALTER TABLE dbo.STOCK_CURRENT ALTER COLUMN EDAD VARCHAR(30) NULL;
ALTER TABLE dbo.STOCK_CURRENT ALTER COLUMN SEXO VARCHAR(20) NULL;
ALTER TABLE dbo.STOCK_CURRENT ALTER COLUMN DET_LINEA VARCHAR(80) NULL;
ALTER TABLE dbo.STOCK_CURRENT ALTER COLUMN DTALLC VARCHAR(150) NULL;
ALTER TABLE dbo.STOCK_CURRENT ALTER COLUMN TALLC VARCHAR(30) NULL;
