IF OBJECT_ID('dbo.STOCK_GRIDS','U') IS NULL
BEGIN
  CREATE TABLE dbo.STOCK_GRIDS (
    ID_GRID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_STOCK_GRIDS PRIMARY KEY,
    ID_EMPRESA INT NOT NULL,
    NAME NVARCHAR(150) NOT NULL,
    RULES_JSON NVARCHAR(MAX) NOT NULL,
    ACTIVE BIT NOT NULL CONSTRAINT DF_GRIDS_ACTIVE DEFAULT 1,
    VERSION INT NOT NULL CONSTRAINT DF_GRIDS_VERSION DEFAULT 1,
    CREATED_BY INT NOT NULL,
    UPDATED_BY INT NOT NULL,
    CREATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_GRIDS_CREATED DEFAULT SYSDATETIME(),
    UPDATED_AT DATETIME2(0) NOT NULL CONSTRAINT DF_GRIDS_UPDATED DEFAULT SYSDATETIME(),
    CONSTRAINT CK_GRIDS_JSON CHECK (ISJSON(RULES_JSON)=1),
    CONSTRAINT FK_GRIDS_EMPRESA FOREIGN KEY(ID_EMPRESA) REFERENCES dbo.EMPRESAS(ID_EMPRESA),
    CONSTRAINT FK_GRIDS_CREATOR FOREIGN KEY(ID_EMPRESA,CREATED_BY) REFERENCES dbo.USERS(ID_EMPRESA,ID_USER),
    CONSTRAINT FK_GRIDS_UPDATER FOREIGN KEY(ID_EMPRESA,UPDATED_BY) REFERENCES dbo.USERS(ID_EMPRESA,ID_USER)
  );
  CREATE UNIQUE INDEX UQ_GRID_ACTIVE_NAME ON dbo.STOCK_GRIDS(ID_EMPRESA,NAME) WHERE ACTIVE=1;
END;
