IF COL_LENGTH('dbo.STOCK_GRIDS','EXPORT_ENABLED') IS NULL
BEGIN
  ALTER TABLE dbo.STOCK_GRIDS ADD
    EXPORT_ENABLED BIT NOT NULL CONSTRAINT DF_GRID_EXPORT_ENABLED DEFAULT 0,
    EXPORT_TIME CHAR(5) NULL,
    EXPORT_PATH NVARCHAR(400) NULL,
    EXPORT_LAST_DATE DATE NULL,
    EXPORT_STATUS VARCHAR(20) NULL,
    EXPORT_FINISHED_AT DATETIMEOFFSET NULL,
    EXPORT_ERROR NVARCHAR(2000) NULL;
END;
GO
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE name='UX_GRID_EXPORT_PATH' AND object_id=OBJECT_ID('dbo.STOCK_GRIDS'))
  CREATE UNIQUE INDEX UX_GRID_EXPORT_PATH ON dbo.STOCK_GRIDS(EXPORT_PATH)
    WHERE ACTIVE=1 AND EXPORT_ENABLED=1 AND EXPORT_PATH IS NOT NULL;
