IF COL_LENGTH('dbo.STOCK_CURRENT','MARCA') IS NULL
  ALTER TABLE dbo.STOCK_CURRENT ADD MARCA NVARCHAR(150) NULL;
IF COL_LENGTH('dbo.STOCK_CURRENT','LISTA') IS NULL
  ALTER TABLE dbo.STOCK_CURRENT ADD LISTA NVARCHAR(30) NULL;
IF COL_LENGTH('dbo.STOCK_CURRENT','VERSION') IS NULL
  ALTER TABLE dbo.STOCK_CURRENT ADD VERSION NVARCHAR(30) NULL;
