IF OBJECT_ID('dbo.STOCK_PRICES','U') IS NULL
BEGIN
  CREATE TABLE dbo.STOCK_PRICES (
    ID_EMPRESA INT NOT NULL REFERENCES dbo.EMPRESAS(ID_EMPRESA),
    COD_ALFA VARCHAR(30) NOT NULL,
    DEPOSITO INT NOT NULL,
    NIVEL INT NOT NULL,
    LISTA NVARCHAR(30) NOT NULL,
    VERSION NVARCHAR(30) NOT NULL,
    PRECIO DECIMAL(19,4) NOT NULL,
    P_BAS DECIMAL(19,4) NULL,
    DTOESP DECIMAL(9,3) NULL,
    CONSTRAINT PK_STOCK_PRICES PRIMARY KEY(ID_EMPRESA,COD_ALFA,DEPOSITO,NIVEL,LISTA,VERSION)
  );
END;
