IF OBJECT_ID('dbo.COMPANY_PRICE_FACTORS','U') IS NULL
BEGIN
  CREATE TABLE dbo.COMPANY_PRICE_FACTORS (
    ID_EMPRESA INT NOT NULL REFERENCES dbo.EMPRESAS(ID_EMPRESA),
    MARCA NVARCHAR(150) NOT NULL,
    NIVEL INT NOT NULL CHECK (NIVEL IN (900,950)),
    FACTOR DECIMAL(9,4) NOT NULL CHECK (FACTOR>0),
    CONSTRAINT PK_COMPANY_PRICE_FACTORS PRIMARY KEY(ID_EMPRESA,MARCA,NIVEL)
  );
END;
