IF COL_LENGTH('dbo.COMPANY_PRICE_FACTORS','ESPECIFICO') IS NULL
BEGIN
 ALTER TABLE dbo.COMPANY_PRICE_FACTORS ADD ESPECIFICO BIT NOT NULL CONSTRAINT DF_FACTOR_SCOPE DEFAULT 0,
 LICENCIA NVARCHAR(150) NOT NULL CONSTRAINT DF_FACTOR_LICENSE DEFAULT N'',
 RUBRO NVARCHAR(40) NOT NULL CONSTRAINT DF_FACTOR_RUBRO DEFAULT N'';
 ALTER TABLE dbo.COMPANY_PRICE_FACTORS DROP CONSTRAINT PK_COMPANY_PRICE_FACTORS;
END;
IF NOT EXISTS(SELECT 1 FROM sys.key_constraints WHERE name='PK_COMPANY_PRICE_FACTORS')
 EXEC(N'ALTER TABLE dbo.COMPANY_PRICE_FACTORS ADD CONSTRAINT PK_COMPANY_PRICE_FACTORS PRIMARY KEY(ID_EMPRESA,MARCA,NIVEL,ESPECIFICO,LICENCIA,RUBRO)');
