IF COL_LENGTH('dbo.COMPANY_PRICE_FACTORS','LISTA') IS NULL
BEGIN
 ALTER TABLE dbo.COMPANY_PRICE_FACTORS ADD LISTA NVARCHAR(30) NOT NULL CONSTRAINT DF_FACTOR_LIST DEFAULT N'';
 ALTER TABLE dbo.COMPANY_PRICE_FACTORS DROP CONSTRAINT PK_COMPANY_PRICE_FACTORS;
END;
IF NOT EXISTS(SELECT 1 FROM sys.key_constraints WHERE name='PK_COMPANY_PRICE_FACTORS')
 EXEC(N'ALTER TABLE dbo.COMPANY_PRICE_FACTORS ADD CONSTRAINT PK_COMPANY_PRICE_FACTORS PRIMARY KEY(ID_EMPRESA,MARCA,NIVEL,ESPECIFICO,LICENCIA,RUBRO,LISTA)');
